import { env } from 'process';
import { registry } from '../src/discord/commands/registry';
import { APIApplicationCommand, RESTPostAPIApplicationCommandsJSONBody, RouteBases, Routes } from 'discord-api-types/v10';
import { CommandRegistry } from '../src/types';

// This script is responsible for registering the bot's commands with Discord's API.
// It uses the command registry generated by `generate-registry.ts` to get the command data and then makes API calls to register them.

const args = process.argv.slice(2);

const discordApplicationId = args[0] || env.DISCORD_APPLICATION_ID;
if (!discordApplicationId) {
	console.error('Error: Discord application ID not provided and DISCORD_APPLICATION_ID environment variable is not set.');
	process.exit(1);
}

const discordBotToken = args[1] || env.DISCORD_BOT_TOKEN;
if (!discordBotToken) {
	console.error('Error: Discord bot token not provided and DISCORD_BOT_TOKEN environment variable is not set.');
	process.exit(1);
}

if (!registry || typeof registry !== 'object') {
	console.error('Error: Command registry is not properly defined. Please run `pnpm generate:registry` to regenerate it.');
	process.exit(1);
}

const registrationUrl = RouteBases.api + Routes.applicationCommands(discordApplicationId);

async function getRegisteredCommands() {
	const response = await fetch(registrationUrl, {
		method: 'GET',
		headers: {
			Authorization: `Bot ${discordBotToken}`,
		},
	});
	return response.json() as Promise<APIApplicationCommand[]>;
}

async function registerCommands(commands: RESTPostAPIApplicationCommandsJSONBody[]) {
	return fetch(registrationUrl, {
		method: 'PUT',
		headers: {
			'Content-Type': 'application/json',
			Authorization: `Bot ${discordBotToken}`,
		},
		body: JSON.stringify(commands),
	});
}

function getCommandData(registry: CommandRegistry): RESTPostAPIApplicationCommandsJSONBody[] {
	let commandList = [];
	for (const [type, commands] of Object.entries(registry))
		for (const [name, command] of Object.entries(commands)) commandList.push(command.data);

	return commandList as RESTPostAPIApplicationCommandsJSONBody[];
}
